# Generated by Django 2.2.19 on 2022-12-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221128_1218'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='follow_not_author'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='Follow',
        ),
    ]
